In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [235]:
data = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

In [236]:
def splitSequence(seq, n_steps):
    
    X = []
    y = []
    if len(seq) <= 5:
        seq_X, seq_y = seq[0:len(seq)-1], seq[len(seq)-1]
        X.append(seq_X)
        y.append(seq_y)
    else:
        for i in range(len(seq)):
            lastIndex = i + n_steps


            if lastIndex > len(seq) - 1:
                break

            seq_X, seq_y = seq[i:lastIndex], seq[lastIndex]

            X.append(seq_X)
            y.append(seq_y)
            pass
    
    X = np.array(X)
    y = np.array(y)
    
    return X,y 

In [237]:
def make_sequence(first_num, n_num, gap):
    X = []
    y = []
    number = first_num
    X.append(number)
    for i in range(n_num-1):
        number = number+gap
        X.append(number)
    y.append(number+gap)
    return X, y

In [238]:
n_steps = 5
if len(data) <= n_steps:
    n_steps = len(data)-1
X, y = splitSequence(data, n_steps)

In [239]:
for i in range(len(X)):
    print(X[i], y[i])

[1 2 3 4 5] 6
[2 3 4 5 6] 7
[3 4 5 6 7] 8
[4 5 6 7 8] 9
[5 6 7 8 9] 10
[ 6  7  8  9 10] 11
[ 7  8  9 10 11] 12
[ 8  9 10 11 12] 13
[ 9 10 11 12 13] 14
[10 11 12 13 14] 15
[11 12 13 14 15] 16
[12 13 14 15 16] 17
[13 14 15 16 17] 18
[14 15 16 17 18] 19
[15 16 17 18 19] 20


In [240]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
print(X[:2])

[[[1]
  [2]
  [3]
  [4]
  [5]]

 [[2]
  [3]
  [4]
  [5]
  [6]]]


In [241]:
model = tf.keras.Sequential()
model.add(layers.LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(layers.Dense(1))

In [242]:
model.summary()

Model: "sequential_15"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_15 (LSTM)              (None, 50)                10400     
                                                                 
 dense_15 (Dense)            (None, 1)                 51        
                                                                 
Total params: 10,451
Trainable params: 10,451
Non-trainable params: 0
_________________________________________________________________


In [243]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.01), loss=tf.keras.losses.MeanSquaredError(), metrics=['accuracy'])

In [244]:
model.fit(X, y, epochs=100, verbose=1)

Epoch 1/100
1/1 [==============================] - 1s 1s/step - loss: 122.0958 - accuracy: 0.0000e+00
Epoch 2/100
1/1 [==============================] - 0s 4ms/step - loss: 63.5297 - accuracy: 0.0000e+00
Epoch 3/100
1/1 [==============================] - 0s 4ms/step - loss: 21.5176 - accuracy: 0.0000e+00
Epoch 4/100
1/1 [==============================] - 0s 4ms/step - loss: 14.3829 - accuracy: 0.0000e+00
Epoch 5/100
1/1 [==============================] - 0s 4ms/step - loss: 29.8767 - accuracy: 0.0000e+00
Epoch 6/100
1/1 [==============================] - 0s 4ms/step - loss: 19.5031 - accuracy: 0.0000e+00
Epoch 7/100
1/1 [==============================] - 0s 4ms/step - loss: 9.2142 - accuracy: 0.0000e+00
Epoch 8/100
1/1 [==============================] - 0s 5ms/step - loss: 6.6676 - accuracy: 0.0000e+00
Epoch 9/100
1/1 [==============================] - 0s 5ms/step - loss: 9.1201 - accuracy: 0.0000e+00
Epoch 10/100
1/1 [==============================] - 0s 5ms/step - loss: 11.6440 - acc

In [247]:
test_data = np.array([5,6,7,8,9])
test_data = test_data.reshape((1, n_steps, n_features))
test_data

array([[[5],
        [6],
        [7],
        [8],
        [9]]])

In [248]:
predictNextNumber = model.predict(test_data, verbose=1)
print(predictNextNumber)

1/1 [==============================] - 0s 16ms/step
[[10.076194]]
